### ISSUE TITLE
[BUG] Build error in create-react-app-example

### ISSUE THREAD

**Issue by CrystalDesignDR** [Crystal-Design-GmbH/divaIntegrationSamples#8]
**Describe the bug**
The build of create-react-app-example fails with an error code

**To Reproduce**
1. Go to 'cd create-react-app-example'
2. Execute 'yarn build'

**Expected behavior**
Build passes with no errors

**Screenshots**
![error](https://user-images.githubusercontent.com/48206301/174037201-fa4905aa-ddf3-4dc5-be81-c72c173327b8.png)

**Additional context**
```$ yarn build
yarn run v1.22.18
$ react-scripts build
(node:10060) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at C:\git\divaIntegrationSamples\create-react-app-example\node_modules\postcss-safe-parser\node_modules\postcss\package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/@crystaldesign/content-box/build/esm/index-d2ab5e70.js:17:12

Read more here: https://cra.link/failed-to-minify

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by chidera-ovuoba** [comment]
If you're seeing this error, you're likely using an old version of react-scripts. You can either fix it by avoiding a dependency that uses modern syntax, or by upgrading to react-scripts@>=2.0.0 and following the migration instructions in the changelog.

**Comment by chidera-ovuoba** [comment]
the most likely issue is that you just need to upgrade the react-scripts dependency in the package.json because you might be using a modern syntax

**Comment by CrystalDesignDR** [comment]
> the most likely issue is that you just need to upgrade the react-scripts dependency in the package.json because you might be using a modern syntax

Hi @chidera-ovuoba and thanks for commenting on this, since our react-scripts version is "react-scripts": "4.0.3" this shouldn't be the issue

**Comment by chidera-ovuoba** [comment]
@CrystalDesignDR  is there any chance you can explain to me the problem better

**Comment by CrystalDesignDR** [comment]
Closing this, since no one ever used CRA anyways. Just use Vite, NX or whatever.
